//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFexp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class empd
    {
        [Key] public int empid { get; set; }
        public string empname { get; set; }
        public string gender { get; set; }
        public string deptname { get; set; }
        public string degname { get; set; }
    }

    public partial class employee
    {
        public int empid { get; set; }
        public string empname { get; set; }
        public string gender { get; set; }
        public string emailid { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string empphoto { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<int> desgid { get; set; }
    
        public virtual department department { get; set; }
        public virtual designation designation { get; set; }
    }
}
