//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorise_Authenticate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPID { get; set; }
        public string EMPNAME { get; set; }
        public Nullable<double> SALARY { get; set; }
        public string DESIGNATION { get; set; }
    }
}
