//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.jobs = new HashSet<job>();
        }
    
        public int department_id { get; set; }
        public string department_name { get; set; }
        public string department_manager { get; set; }
        public string manager_employee_id { get; set; }
    
        public virtual ICollection<job> jobs { get; set; }
    }
}
