//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int eduid { get; set; }
        public string username { get; set; }
        public string class_x { get; set; }
        public string class_xii { get; set; }
        public string bachelors { get; set; }
        public string masters { get; set; }
        public string diploma { get; set; }
    
        public virtual user user { get; set; }
    }
}
