//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class experience
    {
        public int expid { get; set; }
        public string username { get; set; }
        public string company_1 { get; set; }
        public string role_1 { get; set; }
        public Nullable<int> years_1 { get; set; }
        public string company_2 { get; set; }
        public string role_2 { get; set; }
        public Nullable<int> years_2 { get; set; }
        public string company_3 { get; set; }
        public string role_3 { get; set; }
        public Nullable<int> years_3 { get; set; }
        public string company_4 { get; set; }
        public string role_4 { get; set; }
        public Nullable<int> years_4 { get; set; }
        public string company_5 { get; set; }
        public string role_5 { get; set; }
        public Nullable<int> years_5 { get; set; }
    
        public virtual user user { get; set; }
    }
}
