//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoltecRecruitsEntities : DbContext
    {
        public HoltecRecruitsEntities()
            : base("name=HoltecRecruitsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<applicant> applicants { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<education> educations { get; set; }
        public DbSet<experience> experiences { get; set; }
        public DbSet<job> jobs { get; set; }
        public DbSet<profile> profiles { get; set; }
        public DbSet<skill> skills { get; set; }
        public DbSet<user> users { get; set; }
    }
}
