//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public job()
        {
            this.applicants = new HashSet<applicant>();
        }
    
        public string job_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public string job_title { get; set; }
        public string job_description { get; set; }
        public string salary { get; set; }
        public string experience { get; set; }
    
        public virtual ICollection<applicant> applicants { get; set; }
        public virtual department department { get; set; }
    }
}
