//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int skillid { get; set; }
        public string username { get; set; }
        public Nullable<bool> cplusplus { get; set; }
        public Nullable<bool> javascript { get; set; }
        public Nullable<bool> c_ { get; set; }
        public Nullable<bool> python { get; set; }
        public Nullable<bool> java { get; set; }
        public Nullable<bool> html { get; set; }
        public Nullable<bool> flutter { get; set; }
        public Nullable<bool> aiml { get; set; }
        public Nullable<bool> react { get; set; }
        public Nullable<bool> angular { get; set; }
        public Nullable<bool> autocad { get; set; }
        public Nullable<bool> computer_graphics { get; set; }
    
        public virtual user user { get; set; }
    }
}
