//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.applicants = new HashSet<applicant>();
            this.educations = new HashSet<education>();
            this.experiences = new HashSet<experience>();
            this.profiles = new HashSet<profile>();
            this.skills = new HashSet<skill>();
        }
    
        public string username { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string gender { get; set; }
    
        public virtual ICollection<applicant> applicants { get; set; }
        public virtual ICollection<education> educations { get; set; }
        public virtual ICollection<experience> experiences { get; set; }
        public virtual ICollection<profile> profiles { get; set; }
        public virtual ICollection<skill> skills { get; set; }
    }
}
