//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First_Approach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int Com_Id { get; set; }
        public string Com_Name { get; set; }
        public int Scale { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
    }
}
