//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First_Approach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int Emp_Id { get; set; }
        public double Salary { get; set; }
        public string Emp_Name { get; set; }
        public int companyCom_Id { get; set; }
    
        public virtual company company { get; set; }
    }
}
