//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19July.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDETAIL
    {
        public string STUNAME { get; set; }
        public Nullable<double> ENGMARKS { get; set; }
        public Nullable<double> SCIMARKS { get; set; }
        public Nullable<double> MATHMARKS { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> PER { get; set; }
        public string GRADE { get; set; }

        public void Grading()
        {
            TOTAL = (ENGMARKS + SCIMARKS + MATHMARKS);
            PER = TOTAL / 3;
            if (PER > 90) { GRADE = "Distinction"; }
            else if (PER > 75) { GRADE = "First Class"; }
            else if (PER > 60) { GRADE = "Second Class"; }
            else if (PER > 45) { GRADE = "Pass"; }
            else { GRADE = "Fail"; }
        }
    }
}
