//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _30July.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.States = new HashSet<State>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> ContinentID { get; set; }
    
        public virtual Continent Continent { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
