//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedinPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int postid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string headline { get; set; }
        public string postext { get; set; }
        public Nullable<int> profileid { get; set; }
    
        public virtual profile profile { get; set; }
    }
}
